# Generated by Django 3.2.6 on 2024-12-13 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='Unique identifier for the batch', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='home.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'batch')},
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='document',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='peerevaluation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseRole',
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='home.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='home.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incentivization',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='home.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statistics',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='home.batch'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='incentivization',
            unique_together={('batch', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('course', 'batch_id', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='incentivization',
            name='course',
        ),
    ]
