# Generated by Django 3.2.6 on 2024-12-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20241213_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=0, help_text='Unique identifier for the course', max_length=100),
            preserve_default=False,
        ),
    ]
