# Generated by Django 3.2.6 on 2024-12-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='uid',
            field=models.CharField(default=0, help_text='Unique identifier for the student', max_length=100),
            preserve_default=False,
        ),
    ]
