# Generated by Django 3.2.6 on 2024-12-13 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_studentenrollment_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='home.course'),
            preserve_default=False,
        ),
    ]
