# Generated by Django 3.2.6 on 2024-12-13 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_studentenrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='teaching_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches_as_ta', to=settings.AUTH_USER_MODEL),
        ),
    ]
