# Generated by Django 3.2.6 on 2024-12-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_batch_teaching_assistant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_mapping',
        ),
    ]
