# Generated by Django 3.2.6 on 2024-12-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_student_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='uid',
            field=models.CharField(blank=True, help_text='Unique identifier for the student', max_length=100, null=True),
        ),
    ]
