# Generated by Django 3.2.6 on 2024-12-16 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_studentenrollment_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='home.batch'),
        ),
    ]
