# Generated by Django 3.2.6 on 2024-12-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_studentenrollment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='approval_status',
            field=models.BooleanField(default=False, help_text='Indicates whether the enrollment is approved'),
        ),
    ]
