# Generated by Django 3.2.6 on 2024-12-21 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_studentenrollment_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingAssistantAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_associations', to='home.batch')),
                ('teaching_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_associations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('batch', 'teaching_assistant')},
            },
        ),
    ]
