# Generated by Django 3.2.6 on 2024-12-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_teachingassistantassociation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='teaching_assistant',
        ),
    ]
