# Generated by Django 3.2.6 on 2024-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20241226_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
