# Generated by Django 3.2.6 on 2024-12-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20241226_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staffs',
        ),
    ]
