# Generated by Django 3.2.6 on 2024-12-30 06:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_delete_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 12, 2, 46, 767757)),
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='evaluated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='peer_evaluations', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='uid',
            field=models.IntegerField(default=0, help_text='Unique identifier for the user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='score',
            field=models.TextField(help_text='Score for the evaluation'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.exam')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_evaluations', to='home.documents'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
