# Generated by Django 3.2.6 on 2024-12-30 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_peerevaluation_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='uid',
            field=models.CharField(default=0, help_text='Unique identifier for the user', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 12, 16, 11, 685673)),
        ),
    ]
