# Generated by Django 3.2.6 on 2024-12-30 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20241230_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='k',
            field=models.IntegerField(default=0, help_text='Number of evaluations for student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 14, 13, 53, 27790)),
        ),
    ]
