# Generated by Django 3.2.6 on 2025-01-01 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20250101_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peerevaluation',
            old_name='student',
            new_name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 14, 59, 32, 989998)),
        ),
    ]
