# Generated by Django 3.2.6 on 2025-01-01 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20250101_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peerevaluation',
            old_name='uploaded_by',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 8, 15, 3, 56, 742489)),
        ),
    ]
