# Generated by Django 3.2.6 on 2025-01-02 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20250101_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmevaluation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 9, 27, 31, 335365)),
        ),
    ]
