# Generated by Django 3.2.6 on 2025-01-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_peerevaluation_deadline'),
        ('home', '0033_auto_20250102_1638'),
    ]

    operations = [
    ]
