# Generated by Django 3.2.6 on 2025-01-03 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_merge_20250103_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 9, 59, 0, 758333)),
        ),
    ]
