# Generated by Django 3.2.6 on 2025-01-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_merge_20250103_1010'),
        ('home', '0036_alter_peerevaluation_deadline'),
    ]

    operations = [
    ]
