# Generated by Django 3.2.6 on 2025-01-07 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_merge_20250103_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 14, 12, 33, 40, 44532)),
        ),
    ]
