# Generated by Django 3.2.6 on 2025-01-08 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_peerevaluation_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='flags',
            field=models.BooleanField(default=False, help_text='Indicates whether the evaluation is flagged'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 14, 43, 21, 661885)),
        ),
    ]
