# Generated by Django 3.2.6 on 2025-01-08 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20250108_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peerevaluation',
            name='evaluations_sent',
        ),
        migrations.AddField(
            model_name='exam',
            name='evaluations_sent',
            field=models.BooleanField(default=False, help_text='Indicates whether the evaluations are sent'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 15, 15, 32, 20, 315900)),
        ),
    ]
