# Generated by Django 3.2.6 on 2025-01-09 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20250108_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentivization',
            name='exam_count',
            field=models.IntegerField(default=0, help_text='Number of exams attempted by the student'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 19, 11, 656040)),
        ),
    ]
