# Generated by Django 3.2.6 on 2025-01-09 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20250109_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incentivization',
            name='exam_count',
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 14, 20, 8, 243597)),
        ),
    ]
