# Generated by Django 3.2.6 on 2025-01-09 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20250109_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivization',
            name='rewards',
            field=models.FloatField(help_text='Rewards for the student'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 16, 16, 51, 29, 128349)),
        ),
    ]
