# Generated by Django 3.2.6 on 2025-01-11 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20250109_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 18, 15, 3, 33, 582803)),
        ),
    ]
