# Generated by Django 5.1.4 on 2025-01-15 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20250111_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopic',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 10, 7, 4, 494848)),
        ),
    ]
