# Generated by Django 5.1.4 on 2025-01-15 04:54

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_coursetopic_date_alter_peerevaluation_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 10, 24, 2, 258239)),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('student', 'course', 'batch')},
        ),
    ]
