# Generated by Django 5.1.4 on 2025-01-15 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_peerevaluation_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 12, 8, 13, 174925)),
        ),
    ]
