# Generated by Django 3.2.6 on 2025-01-16 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_peerevaluation_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 14, 38, 8, 19434)),
        ),
    ]
