# Generated by Django 5.1.5 on 2025-01-16 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0051_alter_peerevaluation_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peerevaluation",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 11, 27, 58, 455613)
            ),
        ),
    ]
