# Generated by Django 5.1.5 on 2025-02-03 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_peerevaluation_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='solutions',
            field=models.FileField(null=True, upload_to='apps/static/documents/'),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 14, 28, 47, 597425)),
        ),
    ]
