# Generated by Django 5.1.5 on 2025-02-04 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_exam_solutions_alter_peerevaluation_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 9, 39, 6, 616191)),
        ),
    ]
