# Generated by Django 5.1.6 on 2025-02-10 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_alter_peerevaluation_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerevaluation',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 21, 49, 21, 332794)),
        ),
    ]
