# Generated by Django 5.1.4 on 2024-12-13 09:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='peer_evaluations',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='user_id',
        ),
        migrations.AddField(
            model_name='numberofquestions',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='evaluated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='ticket',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='numberofquestions',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peerevaluation',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='peer_evaluations', to='app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('student_id', 'course_id'), name='unique_student_course'),
        ),
        migrations.AddField(
            model_name='document',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_documents', to='app.course'),
        ),
        migrations.AddField(
            model_name='document',
            name='peer_evaluations',
            field=models.ManyToManyField(related_name='evaluated_documents', to='app.peerevaluation'),
        ),
        migrations.AddField(
            model_name='document',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to='app.student'),
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peerevaluation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_peer_evaluations', to='app.document'),
        ),
        migrations.DeleteModel(
            name='documents',
        ),
    ]
