# Generated by Django 3.0.7 on 2024-12-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241210_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerevaluation',
            name='ticket',
            field=models.IntegerField(default=0),
        ),
    ]
