# Generated by Django 5.1.4 on 2024-12-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_peerevaluation_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberofquestions',
            name='k',
            field=models.IntegerField(default=0),
        ),
    ]
